export const load = {
    LOADING : "LOADING",
    LOADING_SUCCESS : "LOADING_SUCEESS",
    ADD_TODO : "ADD_TODO",
    SETEDIT_TODO : "SETEDIT_TODO",
    UPDATE_TODO : "UPDATE_TODO",
    REMOVE_TODO : "REMOVE_TODO",
    MARK_TODO : "MARK_TODO",
  }